-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.3 (64-bit) Schlumberger
-- User name   : BCHUAH
-- Date        : Wednesday, November 15 2017 16:22:20
-- Project     : BaseCase367.pet
-- Generated ]

WSTAT                                  -- Generated : Petrel
 /

WWGR                                   -- Generated : Petrel
 /

GWGR                                   -- Generated : Petrel
 /

WTHP                                   -- Generated : Petrel
 /

FGIPL                                  -- Generated : Petrel

FGIP                                   -- Generated : Petrel

FGIPG                                  -- Generated : Petrel

FOIP                                   -- Generated : Petrel

ROIP                                   -- Generated : Petrel
 /

FWCT                                   -- Generated : Petrel

WWCT                                   -- Generated : Petrel
 /

GWCT                                   -- Generated : Petrel
 /

FRS                                    -- Generated : Petrel

RRS                                    -- Generated : Petrel
 /

FGOR                                   -- Generated : Petrel

WGOR                                   -- Generated : Petrel
 /

GGOR                                   -- Generated : Petrel
 /

WBGLR                                  -- Generated : Petrel
 /

FGLR                                   -- Generated : Petrel

WGLR                                   -- Generated : Petrel
 /

GGLR                                   -- Generated : Petrel
 /

FWPR                                   -- Generated : Petrel

WWPR                                   -- Generated : Petrel
 /

RWPR                                   -- Generated : Petrel
 /

GWPR                                   -- Generated : Petrel
 /

FVPR                                   -- Generated : Petrel

WVPR                                   -- Generated : Petrel
 /

GVPR                                   -- Generated : Petrel
 /

FOPR                                   -- Generated : Petrel

WOPR                                   -- Generated : Petrel
 /

ROPR                                   -- Generated : Petrel
 /

GOPR                                   -- Generated : Petrel
 /

WOPP2                                  -- Generated : Petrel
 /

GOPP2                                  -- Generated : Petrel
 /

FOPP                                   -- Generated : Petrel

WOPP                                   -- Generated : Petrel
 /

GOPP                                   -- Generated : Petrel
 /

FLPR                                   -- Generated : Petrel

WLPR                                   -- Generated : Petrel
 /

GLPR                                   -- Generated : Petrel
 /

FGPR                                   -- Generated : Petrel

WGPR                                   -- Generated : Petrel
 /

RGPR                                   -- Generated : Petrel
 /

GGPR                                   -- Generated : Petrel
 /

FNQR                                   -- Generated : Petrel

FAQR                                   -- Generated : Petrel

ALQR                                   -- Generated : Petrel
 /

ANQR                                   -- Generated : Petrel
 /

AAQR                                   -- Generated : Petrel
 /

FPRH                                   -- Generated : Petrel

RPRH                                   -- Generated : Petrel
 /

WBP9                                   -- Generated : Petrel
 /

WBP5                                   -- Generated : Petrel
 /

WBP4                                   -- Generated : Petrel
 /

FPRP                                   -- Generated : Petrel

RPRP                                   -- Generated : Petrel
 /

FPR                                    -- Generated : Petrel

WBP                                    -- Generated : Petrel
 /

RPR                                    -- Generated : Petrel
 /

GPR                                    -- Generated : Petrel
 /

ANQP                                   -- Generated : Petrel
 /

AAQP                                   -- Generated : Petrel
 /

WBHP                                   -- Generated : Petrel
 /

GWPRL                                  -- Generated : Petrel
 /

GVPRL                                  -- Generated : Petrel
 /

GOPRL                                  -- Generated : Petrel
 /

GLPRL                                  -- Generated : Petrel
 /

GGPRL                                  -- Generated : Petrel
 /

FWPRH                                  -- Generated : Petrel

WWPRH                                  -- Generated : Petrel
 /

GWPRH                                  -- Generated : Petrel
 /

FWPTH                                  -- Generated : Petrel

WWPTH                                  -- Generated : Petrel
 /

GWPTH                                  -- Generated : Petrel
 /

FWCTH                                  -- Generated : Petrel

WWCTH                                  -- Generated : Petrel
 /

GWCTH                                  -- Generated : Petrel
 /

FOPRH                                  -- Generated : Petrel

WOPRH                                  -- Generated : Petrel
 /

GOPRH                                  -- Generated : Petrel
 /

FOPTH                                  -- Generated : Petrel

WOPTH                                  -- Generated : Petrel
 /

GOPTH                                  -- Generated : Petrel
 /

FLPRH                                  -- Generated : Petrel

WLPRH                                  -- Generated : Petrel
 /

GLPRH                                  -- Generated : Petrel
 /

FGORH                                  -- Generated : Petrel

WGORH                                  -- Generated : Petrel
 /

GGORH                                  -- Generated : Petrel
 /

FGLRH                                  -- Generated : Petrel

WGLRH                                  -- Generated : Petrel
 /

GGLRH                                  -- Generated : Petrel
 /

FGPRH                                  -- Generated : Petrel

WGPRH                                  -- Generated : Petrel
 /

GGPRH                                  -- Generated : Petrel
 /

FGPTH                                  -- Generated : Petrel

WGPTH                                  -- Generated : Petrel
 /

GGPTH                                  -- Generated : Petrel
 /

WBHPH                                  -- Generated : Petrel
 /

FWVIS                                  -- Generated : Petrel

FWSAT                                  -- Generated : Petrel

FWDEN                                  -- Generated : Petrel

FOVIS                                  -- Generated : Petrel

FOSAT                                  -- Generated : Petrel

FGVIS                                  -- Generated : Petrel

FGSAT                                  -- Generated : Petrel

FWPT                                   -- Generated : Petrel

WWPT                                   -- Generated : Petrel
 /

GWPT                                   -- Generated : Petrel
 /

FGPTS                                  -- Generated : Petrel

WGPTS                                  -- Generated : Petrel
 /

GGPTS                                  -- Generated : Petrel
 /

FVPT                                   -- Generated : Petrel

WVPT                                   -- Generated : Petrel
 /

GVPT                                   -- Generated : Petrel
 /

FOPT                                   -- Generated : Petrel

WOPT                                   -- Generated : Petrel
 /

ROPT                                   -- Generated : Petrel
 /

GOPT                                   -- Generated : Petrel
 /

FGPT                                   -- Generated : Petrel

WGPT                                   -- Generated : Petrel
 /

RGPT                                   -- Generated : Petrel
 /

GGPT                                   -- Generated : Petrel
 /

FNQT                                   -- Generated : Petrel

FAQT                                   -- Generated : Petrel

ALQT                                   -- Generated : Petrel
 /

WPI9                                   -- Generated : Petrel
 /

WPI5                                   -- Generated : Petrel
 /

WPI4                                   -- Generated : Petrel
 /

WPI1                                   -- Generated : Petrel
 /

WPI                                    -- Generated : Petrel
 /

FOEWW                                  -- Generated : Petrel

ROEWW                                  -- Generated : Petrel
 /

FOEWG                                  -- Generated : Petrel

ROEWG                                  -- Generated : Petrel
 /

FOEW                                   -- Generated : Petrel

ROEW                                   -- Generated : Petrel
 /

PERFORMA                               -- Generated : Petrel

WGORL
 'B1' 1 /
 'B1' 2 /
/

WWCTL
 'B1' 1 /
 'B1' 2 /
/

WVFRL
 'B1' 1 /
 'B1' 2 /
/

WLFRL
 'B1' 1 /
 'B1' 2 /
/

WOFRL
 'B1' 1 /
 'B1' 2 /
/

COPR
'*' /
/

CPR
'*' /
/

CPRL
'*'  /
/

CPI
  /

CWCT
'*' /
/

CGOR
'*' /
/

CLFR
'*' /
/

COFR
'*' /
/

