-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.3 (64-bit) Schlumberger
-- User name   : BCHUAH
-- Date        : Wednesday, November 15 2017 16:22:17
-- Project     : BaseCase367.pet
-- Generated ]

INIT                                   -- Generated : Petrel

RPTINIT                                -- Generated : Petrel
  DEPTH DX DY NTG PERMX PERMY PERMZ PORO TRANX TRANY TRANZ /

GRIDFILE                               -- Generated : Petrel
  0 0 /

GRIDUNIT                               -- Generated : Petrel
  FEET /

MAPUNITS                               -- Generated : Petrel
  FEET /

MAPAXES                                -- Generated : Petrel
  1142600.44 2086747.09 1142600.44 2090027.93 1145881.28 2090027.93 /

PINCH                                  -- Generated : Petrel
  /

